apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: diplom
  name: diplom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom
  template:
    metadata:
      labels:
        app: diplom
    spec:
      containers:
        - image: anguisa/diplom_app:latest
          imagePullPolicy: IfNotPresent
          name: diplom-app
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: diplom
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: 32181
  selector:
    app: diplom
  type: NodePort